version: '2'

services:
  mysql:
    container_name: mysql.${DOMAIN}
    network_mode: test
    image: mysql
    expose:
      - 3306
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
  redis:
    container_name: redis.${DOMAIN}
    network_mode: test
    image: redis
    expose:
      - 6379
  web:
    network_mode: test
    image: isotop/php:5.6-apache
    expose:
    - 80
    volumes:
      - .:/var/www/html
    environment:
      - SITEPATH=/var/www/html/web
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
    depends_on:
      - mysql
      - redis
