version: '2'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    image: isotop/php:5.6-apache
    ports:
      - 8888:80
    volumes:
      - .:/var/www/html
    environment:
      - SITEPATH=/var/www/html/web
    links:
      - redis
