version: '2'

services:
  redis:
    container_name: redis.${DOMAIN}
    network_mode: test
    image: redis
    expose:
      - 6379
  web:
    network_mode: test
    image: isotop/php:5.6-apache
    expose:
    - 80
    volumes:
      - .:/var/www/html
    environment:
      - SITEPATH=/var/www/html/web
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
    depends_on:
      - redis
